/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Lovanto
 */
public class Dashboard extends javax.swing.JFrame {

    //this method is to control which menu will be active or non-active
    private void setMenuLogout() {
//        menuLogin.setEnabled(true);
//        menuExit.setEnabled(true);
//        menuBayar.setEnabled(false);
//        menuJasa.setEnabled(false);
//        menuLogout.setEnabled(false);
//        menuPesan.setEnabled(false);
//        menuPengguna.setEnabled(false);
    }
     
    public Dashboard() {
        initComponents();
        setMenuLogout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogLogin = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAuth = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        menuMenu = new javax.swing.JMenu();
        menuPengguna = new javax.swing.JMenuItem();
        menuJasa = new javax.swing.JMenuItem();
        menuBayar = new javax.swing.JMenuItem();
        menuPesan = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();

        dialogLogin.setMinimumSize(new java.awt.Dimension(402, 386));
        dialogLogin.setPreferredSize(new java.awt.Dimension(402, 386));
        dialogLogin.setResizable(false);
        dialogLogin.setSize(new java.awt.Dimension(402, 386));
        dialogLogin.getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Lato", 1, 30)); // NOI18N
        jLabel3.setText("Login");
        dialogLogin.getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 50, 82, 37);

        jLabel4.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel4.setText("Username");
        dialogLogin.getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 120, 63, 17);

        textPassword.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        dialogLogin.getContentPane().add(textPassword);
        textPassword.setBounds(70, 220, 270, 30);

        jLabel5.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        dialogLogin.getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 190, 61, 17);

        textUsername.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        dialogLogin.getContentPane().add(textUsername);
        textUsername.setBounds(70, 150, 270, 30);

        jButton1.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jButton1.setText("Batal");
        dialogLogin.getContentPane().add(jButton1);
        jButton1.setBounds(270, 290, 67, 25);

        jButton2.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jButton2.setText("Login");
        dialogLogin.getContentPane().add(jButton2);
        jButton2.setBounds(70, 290, 160, 25);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flash Laundry Apps");
        setBackground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(546, 252));
        setPreferredSize(new java.awt.Dimension(546, 252));
        setResizable(false);
        setSize(new java.awt.Dimension(546, 252));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 190, 0, 0);

        jLabel1.setText("Selamat Datang di Flash Laundry...");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 180, 240, 14);

        menuAuth.setText("Auth");

        menuLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        menuAuth.add(menuLogin);

        menuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuAuth.add(menuLogout);

        jMenuBar1.add(menuAuth);

        menuMenu.setText("Menu");

        menuPengguna.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuPengguna.setText("User");
        menuPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenggunaActionPerformed(evt);
            }
        });
        menuMenu.add(menuPengguna);

        menuJasa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        menuJasa.setText("Jasa");
        menuMenu.add(menuJasa);

        menuBayar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuBayar.setText("Bayar");
        menuMenu.add(menuBayar);

        menuPesan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuPesan.setText("Pesan");
        menuMenu.add(menuPesan);

        jMenuBar1.add(menuMenu);

        menuExit.setText("Exit");
        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * when menu login clicked do:
     * set text field null, then show dialog login.
    */
    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        textUsername.setText("");
        textPassword.setText("");
        dialogLogin.setVisible(true);
    }//GEN-LAST:event_menuLoginActionPerformed

    /**
     * when menu login clicked make some menu cannot be access 
     * until they login again.
    */
    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        setMenuLogout();
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenggunaActionPerformed
        new Registrasi().show();
    }//GEN-LAST:event_menuPenggunaActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dialogLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAuth;
    private javax.swing.JMenuItem menuBayar;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenuItem menuJasa;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenuItem menuPengguna;
    private javax.swing.JMenuItem menuPesan;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
}
